name: 'Execute SSH commands'
description: 'Execute SSH commands with github actions'
author: 'soasada'
inputs:
  host:
    description: "Hostname or IP address of the server."
    required: true
  username:
    description: "Username for authentication."
    required: true
  port:
    description: "Port number of the server."
    required: true
  key:
    description: "Client private key"
    required: true
  pubkey:
    description: "Server public key"
    required: true
  clientpubkey:
    description: "Client public key"
    required: true
  script:
    description: "Script to execute on the remote server."
    required: true
  args:
    description: "SSH parameters for example: -f."
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.host }}
    - ${{ inputs.username }}
    - ${{ inputs.port }}
    - ${{ inputs.key }}
    - ${{ inputs.pubkey }}
    - ${{ inputs.clientpubkey }}
    - ${{ inputs.script }}
    - ${{ inputs.args }}

branding:
  color: "green"
  icon: "terminal"